

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class AtlasConexion : DbContext
{
    public AtlasConexion()
        : base("name=AtlasConexion")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<TABResource> TABResource { get; set; }

    public virtual DbSet<TABCategory> TABCategory { get; set; }

    public virtual DbSet<TABAttribute> TABAttribute { get; set; }

    public virtual DbSet<TABCost> TABCost { get; set; }

    public virtual DbSet<TABGenerate> TABGenerate { get; set; }

    public virtual DbSet<TABGameObject> TABGameObject { get; set; }

    public virtual DbSet<TABAdmin> TABAdmin { get; set; }

    public virtual DbSet<TABGame> TABGame { get; set; }

    public virtual DbSet<TABPlayer> TABPlayer { get; set; }

    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<TABEvent> TABEvent { get; set; }

    public virtual DbSet<TABNotification> TABNotification { get; set; }

    public virtual DbSet<TABInitialGameObject> TABInitialGameObject { get; set; }

    public virtual DbSet<TABInitialResource> TABInitialResource { get; set; }

    public virtual DbSet<TABActionConfig> TABActionConfig { get; set; }

    public virtual DbSet<TABActionConfigDepends> TABActionConfigDepends { get; set; }

    public virtual DbSet<TABAttackConfig1> TABAttackConfig1Set { get; set; }

    public virtual DbSet<TABGroup> TABGroup { get; set; }

    public virtual DbSet<TABGroupMessage> TABGroupMessage { get; set; }

    public virtual DbSet<TABGroupPlayer> TABGroupPlayer { get; set; }

}

}

