
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TABActionConfigDepends
{

    public int ID_ACTIONCONFIG { get; set; }

    public int ID_GAMEOBJECT { get; set; }

    public int ID_ATTRIBUTE { get; set; }

    public int Value { get; set; }



    public virtual TABActionConfig TABActionConfig { get; set; }

    public virtual TABAttribute TABAttribute { get; set; }

    public virtual TABGameObject TABGameObject { get; set; }

}

}
