
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer.Model
{

using System;
    using System.Collections.Generic;
    
public abstract partial class TABAttackConfig1
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TABAttackConfig1()
    {

        this.TABGameObject = new HashSet<TABGameObject>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public int PercentLoss { get; set; }

    public int PercentGain { get; set; }

    public int ID_GAME_FK { get; set; }



    public virtual TABGame TABGame { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABGameObject> TABGameObject { get; set; }

}

}
