
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TABGroupMessage
{

    public int ID { get; set; }

    public string ID_PLAYER_FK { get; set; }

    public int ID_GROUP_FK { get; set; }

    public string Text { get; set; }

    public byte[] Date { get; set; }



    public virtual TABGroup TABGroup { get; set; }

    public virtual TABPlayer TABPlayer { get; set; }

}

}
