
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TABGameObject
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TABGameObject()
    {

        this.TABAttribute = new HashSet<TABAttribute>();

        this.TABCost = new HashSet<TABCost>();

        this.TABGenerate = new HashSet<TABGenerate>();

        this.TABEvent = new HashSet<TABEvent>();

        this.TABActionConfigDepends = new HashSet<TABActionConfigDepends>();

        this.TABInitialGameObject2 = new HashSet<TABInitialGameObject>();

        this.TABActionConfig = new HashSet<TABActionConfig>();

        this.TABAttackConfig = new HashSet<TABAttackConfig1>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public int ID_CATEGORY_FK { get; set; }

    public string Image { get; set; }

    public string Description { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABAttribute> TABAttribute { get; set; }

    public virtual TABCategory TABCategory { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABCost> TABCost { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABGenerate> TABGenerate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABEvent> TABEvent { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABActionConfigDepends> TABActionConfigDepends { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABInitialGameObject> TABInitialGameObject2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABActionConfig> TABActionConfig { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABAttackConfig1> TABAttackConfig { get; set; }

}

}
