
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TABGame
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TABGame()
    {

        this.TABCategory = new HashSet<TABCategory>();

        this.TABPlayer = new HashSet<TABPlayer>();

        this.TABResource = new HashSet<TABResource>();

        this.TABActionConfig = new HashSet<TABActionConfig>();

        this.TABInitialGameObject = new HashSet<TABInitialGameObject>();

        this.TABInitialResource = new HashSet<TABInitialResource>();

        this.TABAttackConfig = new HashSet<TABAttackConfig1>();

        this.TABGroup = new HashSet<TABGroup>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public string Dominio { get; set; }

    public string CSS { get; set; }

    public string Estado { get; set; }

    public string FacebookAppID { get; set; }

    public Nullable<byte> FacebookAuth { get; set; }

    public string FacebookAppSecret { get; set; }

    public string GoogleClientID { get; set; }

    public string GoogleClientSecret { get; set; }

    public string ID_ADMIN_FK { get; set; }

    public string Logo { get; set; }



    public virtual TABAdmin TABAdmin { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABCategory> TABCategory { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABPlayer> TABPlayer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABResource> TABResource { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABActionConfig> TABActionConfig { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABInitialGameObject> TABInitialGameObject { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABInitialResource> TABInitialResource { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABAttackConfig1> TABAttackConfig { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABGroup> TABGroup { get; set; }

}

}
