
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TABNotification
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TABNotification()
    {

        this.TABEvent = new HashSet<TABEvent>();

    }


    public int ID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ID_PLAYER_FK { get; set; }

    public bool hasRead { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABEvent> TABEvent { get; set; }

    public virtual TABPlayer TABPlayer { get; set; }

}

}
