
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TABPlayer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TABPlayer()
    {

        this.TABNotification = new HashSet<TABNotification>();

        this.TABGroupMessage = new HashSet<TABGroupMessage>();

    }


    public string ID { get; set; }

    public string Nick { get; set; }

    public string Pass { get; set; }

    public string Email { get; set; }

    public string Picture { get; set; }

    public string TokenFacebook { get; set; }

    public string TokenGoogle { get; set; }

    public Nullable<int> ID_GAME_FK { get; set; }



    public virtual TABGame TABGame { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABNotification> TABNotification { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TABGroupMessage> TABGroupMessage { get; set; }

    public virtual TABGroupPlayer TABGroupPlayer { get; set; }

}

}
